(defun save-then-kill-buffer-and-window ()
  (interactive)
  (when (buffer-modified-p) (save_buffer))
  (kill-buffer-and-window))
(defun trim-trailing-whitespace ()
  (interactive)
  (delete-trailing-whitespace)
  (message "Trimmed trailing whitespace"))
(defun org-insert-heading-promote ()
  (interactive)
  (org-insert-heading-after-current)
  (org-promote)
  (evil-insert 1))
(defun org-insert-heading-down ()
  (interactive)
  (if (org-at-item-p)
      (progn
	(evil-append-line 1)
	(org-insert-item (org-at-item-checkbox-p)))
    (progn
      (org-insert-heading-after-current)
      (evil-insert 1))))
(defun org-insert-heading-up ()
  (interactive)
  (if (org-at-item-p)
      (progn
	(evil-beginning-of-line)
	(org-insert-item (org-at-item-checkbox-p)))
    (progn
      (org-back-to-heading)
      (org-insert-heading)
      (end-of-line 1)
      (evil-insert 1))))
(defun org-insert-heading-demote ()
  (interactive)
  (org-insert-heading-after-current)
  (org-demote)
  (evil-insert 1))
